### PR TITLE
Add API for calling Variational Bayesian learning

### PR DESCRIPTION
**Pull request by yuchen1984**

### CODE REVIEW

**Review by thomasathorne — CHANGES_REQUESTED** [review]
Thanks for the pull request! This looks great, and is a very useful addition. Could you add a test that uses the `variational` function? (It could easily just use the `bernoulli.stan` model that already exists in the test resources.) Also, could you add a line in the README file that gives an example of using the new function?

**Comment by yuchen1984** [comment]
Update the readme and test case as requested.

**Review by thomasathorne — APPROVED** [review]

**Comment by thomasathorne** [comment]
I have pushed our pair-programmed rework, and I'll merge this now.

Should have a the new build on clojars this evening. This will be version 0.3.0.

**Comment by yuchen1984** [comment]
Cool

**Pull request merged**
